test_that("we can get the correct interval and level given an integer within, above or below the primary octave", {
  # level = -2
  expect_equal(level_and_interval_for(-25,0),c(level=2,interval=1))
  # level = -1
  expect_equal(level_and_interval_for(-24,0),c(level=1,interval=0))
  expect_equal(level_and_interval_for(-13,0),c(level=1,interval=1))
  # level = 0
  expect_equal(level_and_interval_for(-12,0),c(level=0,interval=0))
  expect_equal(level_and_interval_for(-1,0),c(level=0,interval=1))
  expect_equal(level_and_interval_for(0,0),c(level=0,interval=0))
  expect_equal(level_and_interval_for(1,0),c(level=0,interval=1))
  expect_equal(level_and_interval_for(12,0),c(level=0,interval=12))
  # level = +1
  expect_equal(level_and_interval_for(13,0),c(level=1,interval=1))
  expect_equal(level_and_interval_for(24,0),c(level=1,interval=12))
  # level = +2
  expect_equal(level_and_interval_for(25,0),c(level=2,interval=1))
  expect_equal(level_and_interval_for(36,0),c(level=2,interval=12))
  # level = +3
  expect_equal(level_and_interval_for(37,0),c(level=3,interval=1))
})

test_that("we can get the correct interval and level given a pair of integers within, above or below the primary octave", {
  expect_equal(level_and_interval_for(c(0,4),0),c(level=0,interval=4))
  expect_equal(level_and_interval_for(c(0,7),0),c(level=0,interval=7))
  expect_equal(level_and_interval_for(c(4,7),0),c(level=0,interval=3))
  expect_equal(level_and_interval_for(c(-14,27),0),c(level=3,interval=5))
  expect_equal(level_and_interval_for(c(5,-2),0),c(level=0,interval=7))
  expect_equal(level_and_interval_for(c(7,14),0),c(level=0,interval=7))
})

test_that("we can get the correct integer given a level and position", {
  expect_equal(integer_from_position_and_level(11,-3),-25)
  expect_equal(integer_from_position_and_level(12,-3),-24)
  expect_equal(integer_from_position_and_level(0,-2),-24)
  expect_equal(integer_from_position_and_level(11,-2),-13)
  expect_equal(integer_from_position_and_level(12,-2),-12)
  expect_equal(integer_from_position_and_level(0,-1),-12)
  expect_equal(integer_from_position_and_level(6,-1),-6)
  expect_equal(integer_from_position_and_level(11,-1),-1)
  expect_equal(integer_from_position_and_level(12,-1),0)
  expect_equal(integer_from_position_and_level(0,0),0)
  expect_equal(integer_from_position_and_level(12,0),12)
  expect_equal(integer_from_position_and_level(0,1),12)
  expect_equal(integer_from_position_and_level(1,1),13)
  expect_equal(integer_from_position_and_level(12,1),24)
  expect_equal(integer_from_position_and_level(0,2),24)
  expect_equal(integer_from_position_and_level(1,2),25)
  expect_equal(integer_from_position_and_level(12,2),36)
  expect_equal(integer_from_position_and_level(0,3),36)
  expect_equal(integer_from_position_and_level(1,3),37)
})
test_that("we can get the correct integer given a level and position", {
  expect_equal(position_and_level_from_integer(-25),c(11,-3))
  expect_equal(position_and_level_from_integer(-24),c(0,-2))
  expect_equal(position_and_level_from_integer(-13),c(11,-2))
  expect_equal(position_and_level_from_integer(-12),c(0,-1))
  expect_equal(position_and_level_from_integer(-6),c(6,-1))
  expect_equal(position_and_level_from_integer(-1),c(11,-1))
  expect_equal(position_and_level_from_integer(0),c(0,0))
  expect_equal(position_and_level_from_integer(12),c(12,0))
  expect_equal(position_and_level_from_integer(13),c(1,1))
  expect_equal(position_and_level_from_integer(24),c(12,1))
  expect_equal(position_and_level_from_integer(25),c(1,2))
  expect_equal(position_and_level_from_integer(36),c(12,2))
  expect_equal(position_and_level_from_integer(37),c(1,3))
})
