test_that("harmony for chords meets expectations", {
  expect_error(harmony(c(3,7,10)),'home must be specified or x must contain 0 or 12 or both')
  expect_equal(harmony(c(0,4,7))$affinity,7.667,tolerance=0.001)
  c_major_triad = harmony(c(0,4,7),0,"C Major Triad")
  expect(tibble::is_tibble(c_major_triad),"expected c major triad to be a tibble")
  expect_equal(c_major_triad$semitone,3.67,tolerance=0.001)
  expect_equal(c_major_triad$intervallic_name,"0:4:7")
  expect_equal(c_major_triad$name,"C Major Triad")
  expect_equal(c_major_triad$affinity,7.666,tolerance=0.001)
})
