test_that("we can get the correct integer given a level and position", {
  expect_equal(integer_from_position_and_level(11,-3),-25)
  expect_equal(integer_from_position_and_level(12,-3),-24)
  expect_equal(integer_from_position_and_level(0,-2),-24)
  expect_equal(integer_from_position_and_level(11,-2),-13)
  expect_equal(integer_from_position_and_level(12,-2),-12)
  expect_equal(integer_from_position_and_level(0,-1),-12)
  expect_equal(integer_from_position_and_level(6,-1),-6)
  expect_equal(integer_from_position_and_level(11,-1),-1)
  expect_equal(integer_from_position_and_level(12,-1),0)
  expect_equal(integer_from_position_and_level(0,0),0)
  expect_equal(integer_from_position_and_level(12,0),12)
  expect_equal(integer_from_position_and_level(0,1),12)
  expect_equal(integer_from_position_and_level(1,1),13)
  expect_equal(integer_from_position_and_level(12,1),24)
  expect_equal(integer_from_position_and_level(0,2),24)
  expect_equal(integer_from_position_and_level(1,2),25)
  expect_equal(integer_from_position_and_level(12,2),36)
  expect_equal(integer_from_position_and_level(0,3),36)
  expect_equal(integer_from_position_and_level(1,3),37)
})
test_that("we can get the correct integer given a level and position", {
  expect_equal(position_and_level_from_integer(-25),c(11,-3))
  expect_equal(position_and_level_from_integer(-24),c(0,-2))
  expect_equal(position_and_level_from_integer(-13),c(11,-2))
  expect_equal(position_and_level_from_integer(-12),c(0,-1))
  expect_equal(position_and_level_from_integer(-6),c(6,-1))
  expect_equal(position_and_level_from_integer(-1),c(11,-1))
  expect_equal(position_and_level_from_integer(0),c(0,0))
  expect_equal(position_and_level_from_integer(12),c(12,0))
  expect_equal(position_and_level_from_integer(13),c(1,1))
  expect_equal(position_and_level_from_integer(24),c(12,1))
  expect_equal(position_and_level_from_integer(25),c(1,2))
  expect_equal(position_and_level_from_integer(36),c(12,2))
  expect_equal(position_and_level_from_integer(37),c(1,3))
})
test_that("rotation works", {
  angle = pi/4
  expect_error(rotate(cbind(1,0),angle))
  expect_equal(rotate(rbind(1,0),angle),rbind(cos(angle),sin(angle)))
  expect_equal(rotate(rbind(0,1),angle),rbind(-sin(angle),cos(angle)))
})
test_that("sum_of_prime_factors works", {
  expect_equal(sum_of_prime_factors(numbers::primeFactors(1)),0)
  expect_equal(sum_of_prime_factors(numbers::primeFactors(16)),8)
})
test_that("l1norm works as expected", {
  expect_equal(l1norm(1,1),0)
  expect_equal(l1norm(2,1),l1norm(1,2))
  expect_equal(l1norm(3,2),l1norm(2,3))
  expect_equal(l1norm(c(1,2,1,3,2),c(1,1,2,2,3)),c(0,2,2,5,5))
  expect_equal(l1norm(c(1,2,1,3,2),c(1,1,2,2,3)),l1norm(c(1,1,2,2,3),c(1,2,1,3,2)))
})
test_that("l2norm works as expected", {
  expect_equal(l2norm(1,1),0)
  expect_equal(l2norm(2,1),l2norm(1,2))
  expect_equal(l2norm(3,2),l2norm(2,3))
  expect_equal(l2norm(c(1,2,1,3,2),c(1,1,2,2,3)),l2norm(c(1,1,2,2,3),c(1,2,1,3,2)))
  expect_equal(l2norm(c(1,2,1,3,2),c(1,1,2,2,3)),c(0,2,2,3.60551,3.60551),tolerance=0.001)
})
